version: 1
disable_existing_loggers: false
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: INFO
    filename: root.log

root:
  level: DEBUG
  handlers: [ console, file ]
