general:
  general:
    backend: default
include:
  include_2d: {}
mat_wrap:
  Axis:
    figure: {}
    subplot: {}
  Cmap:
    figure:
      cmap: default
      linscale: 0.01
      linthresh: 0.05
      norm: linear
      vmax: null
      vmin: null
    subplot:
      cmap: default
      linscale: 0.01
      linthresh: 0.05
      norm: linear
      vmax: null
      vmin: null
  Colorbar:
    figure:
      fraction: 0.047
      pad: 0.01
    subplot:
      fraction: 0.047
      pad: 0.01
  ColorbarTickParams:
    figure:
      labelsize: 10
    subplot:
      labelsize: 10
  Figure:
    figure:
      aspect: square
      figsize: (7,7)
    subplot:
      aspect: square
      figsize: auto
  Legend:
    figure:
      fontsize: 12
      include: true
    subplot:
      fontsize: 12
      include: true
  TickParams:
    figure:
      labelsize: 16
    subplot:
      labelsize: 10
  Title:
    figure:
      fontsize: 16
    subplot:
      fontsize: 10
  XLabel:
    figure:
      fontsize: 16
    subplot:
      fontsize: 10
  XTicks:
    figure:
      fontsize: 16
    subplot:
      fontsize: 10
  YLabel:
    figure:
      fontsize: 16
    subplot:
      fontsize: 10
  YTicks:
    figure:
      fontsize: 16
    subplot:
      fontsize: 10
mat_wrap_1d:
  AXVLine:
    figure:
      c: k
    subplot:
      c: k
  YXPlot:
    figure:
      c: k
    subplot:
      c: k
mat_wrap_2d:
  ArrayOverlay:
    figure:
      alpha: 0.5
    subplot:
      alpha: 0.5
  GridPlot:
    figure:
      c: k
    subplot:
      c: k
  GridScatter:
    figure:
      c: k
      marker: .
      s: 1
    subplot:
      c: k
      marker: .
      s: 1
  PatchOverlay:
    figure:
      edgecolor: c
      facecolor: null
    subplot:
      edgecolor: c
      facecolor: null
  VectorFieldQuiver:
    figure:
      alpha: 1.0
      angles: xy
      headlength: 0
      headwidth: 1
      linewidth: 5
      pivot: middle
      units: xy
    subplot:
      alpha: 1.0
      angles: xy
      headlength: 0
      headwidth: 1
      linewidth: 5
      pivot: middle
      units: xy
  VoronoiDrawer:
    figure:
      alpha: 0.7
      edgecolor: k
      linewidth: 0.3
    subplot:
      alpha: 0.7
      edgecolor: k
      linewidth: 0.3
plots_search:
  dynesty:
    cornerplot: true
    cornerpoints: false
    runplot: true
    traceplot: true
  emcee:
    corner: true
    likelihood_series: true
    time_series: true
    trajectories: true
  pyswarms:
    contour: true
    cost_history: true
    time_series: true
    trajectories: true
  ultranest:
    cornerplot: true
    runplot: true
    traceplot: true
  zeus:
    corner: true
    likelihood_series: true
    time_series: true
    trajectories: true
