DynestyStatic:
  corner: true             # Output corner figure (using anestetic) during a non-linear search fit?
DynestyDynamic:
  corner: true             # Output corner figure (using anestetic) during a non-linear search fit?
Emcee:
  corner: true             # Output corner figure (using corner.py) during a non-linear search fit?
Nautilus:
  corner: true             # Output corner figure (using anestetic) during a non-linear search fit?
PySwarmsLobal:
PySwarmsGlobal:
UltraNest:
  corner: true             # Output corner figure (using anestetic) during a non-linear search fit?
Zeus:
  corner: true             # Output corner figure (using corner.py) during a non-linear search fit?