nest:
  corner_anesthetic: true   # Output corner figure (using anestetic) during a non-linear search fit?
mcmc:
  corner_cornerpy: true     # Output corner figure (using corner.py) during a non-linear search fit?
optimize:
  log_likelihood_vs_iteration: true  # Output a plot of the log likelihood versus iteration number?