mock_search:
  MockOptimizer:
    initialize:
      method: prior
    printing:
      silence: false
    prior_passer:
      sigma: 3.0
      use_errors: true
      use_widths: true
    updates:
      iterations_per_update: 2500
      log_every_update: 1
      model_results_every_update: 1
      remove_state_files_at_end: true
      visualize_every_update: 1
  MockSearch:
    initialize:
      method: prior
    printing:
      silence: false
    prior_passer:
      sigma: 3.0
      use_errors: true
      use_widths: true
    search: {}
    updates:
      iterations_per_update: 2500
      log_every_update: 1
      model_results_every_update: 1
      remove_state_files_at_end: true
      visualize_every_update: 1