Gaussian:
  centre:
    gaussian_limits:
      lower: 0.0
      upper: 1.0
    lower_limit: 0.0
    type: Uniform
    upper_limit: 1.0
    width_modifier:
      type: Absolute
      value: 1.0
  normalization:
    gaussian_limits:
      lower: 0.0
      upper: 1.0
    lower_limit: 0.0
    type: Uniform
    upper_limit: 1.0
    width_modifier:
      type: Absolute
      value: 1.0
  sigma:
    gaussian_limits:
      lower: 0.0
      upper: 1.0
    lower_limit: 0.0
    type: Uniform
    upper_limit: 1.0
    width_modifier:
      type: Absolute
      value: 1.0
